/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.tahir.batch.load.users.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the BatchLoadUsers service. Represents a row in the &quot;Batch_BatchLoadUsers&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.tahir.batch.load.users.model.impl.BatchLoadUsersModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.tahir.batch.load.users.model.impl.BatchLoadUsersImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see BatchLoadUsers
 * @generated
 */
@ProviderType
public interface BatchLoadUsersModel
	extends BaseModel<BatchLoadUsers>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a batch load users model instance should use the {@link BatchLoadUsers} interface instead.
	 */

	/**
	 * Returns the primary key of this batch load users.
	 *
	 * @return the primary key of this batch load users
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this batch load users.
	 *
	 * @param primaryKey the primary key of this batch load users
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this batch load users.
	 *
	 * @return the uuid of this batch load users
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this batch load users.
	 *
	 * @param uuid the uuid of this batch load users
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the batch load users ID of this batch load users.
	 *
	 * @return the batch load users ID of this batch load users
	 */
	public long getBatchLoadUsersId();

	/**
	 * Sets the batch load users ID of this batch load users.
	 *
	 * @param batchLoadUsersId the batch load users ID of this batch load users
	 */
	public void setBatchLoadUsersId(long batchLoadUsersId);

	/**
	 * Returns the group ID of this batch load users.
	 *
	 * @return the group ID of this batch load users
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this batch load users.
	 *
	 * @param groupId the group ID of this batch load users
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this batch load users.
	 *
	 * @return the company ID of this batch load users
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this batch load users.
	 *
	 * @param companyId the company ID of this batch load users
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this batch load users.
	 *
	 * @return the user ID of this batch load users
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this batch load users.
	 *
	 * @param userId the user ID of this batch load users
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this batch load users.
	 *
	 * @return the user uuid of this batch load users
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this batch load users.
	 *
	 * @param userUuid the user uuid of this batch load users
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this batch load users.
	 *
	 * @return the user name of this batch load users
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this batch load users.
	 *
	 * @param userName the user name of this batch load users
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this batch load users.
	 *
	 * @return the create date of this batch load users
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this batch load users.
	 *
	 * @param createDate the create date of this batch load users
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this batch load users.
	 *
	 * @return the modified date of this batch load users
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this batch load users.
	 *
	 * @param modifiedDate the modified date of this batch load users
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this batch load users.
	 *
	 * @return the name of this batch load users
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this batch load users.
	 *
	 * @param name the name of this batch load users
	 */
	public void setName(String name);

	@Override
	public BatchLoadUsers cloneWithOriginalValues();

}