/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.tahir.batch.load.users.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.tahir.batch.load.users.model.BatchLoadUsers;
import com.tahir.batch.load.users.model.BatchLoadUsersModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the BatchLoadUsers service. Represents a row in the &quot;Batch_BatchLoadUsers&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>BatchLoadUsersModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BatchLoadUsersImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see BatchLoadUsersImpl
 * @generated
 */
@JSON(strict = true)
public class BatchLoadUsersModelImpl
	extends BaseModelImpl<BatchLoadUsers> implements BatchLoadUsersModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a batch load users model instance should use the <code>BatchLoadUsers</code> interface instead.
	 */
	public static final String TABLE_NAME = "Batch_BatchLoadUsers";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"batchLoadUsersId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"name", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("batchLoadUsersId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Batch_BatchLoadUsers (uuid_ VARCHAR(75) null,batchLoadUsersId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,name VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table Batch_BatchLoadUsers";

	public static final String ORDER_BY_JPQL =
		" ORDER BY batchLoadUsers.batchLoadUsersId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY Batch_BatchLoadUsers.batchLoadUsersId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long BATCHLOADUSERSID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public BatchLoadUsersModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _batchLoadUsersId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setBatchLoadUsersId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _batchLoadUsersId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return BatchLoadUsers.class;
	}

	@Override
	public String getModelClassName() {
		return BatchLoadUsers.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<BatchLoadUsers, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<BatchLoadUsers, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<BatchLoadUsers, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((BatchLoadUsers)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<BatchLoadUsers, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<BatchLoadUsers, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(BatchLoadUsers)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<BatchLoadUsers, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<BatchLoadUsers, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<BatchLoadUsers, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<BatchLoadUsers, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<BatchLoadUsers, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<BatchLoadUsers, Object>>();
		Map<String, BiConsumer<BatchLoadUsers, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<BatchLoadUsers, ?>>();

		attributeGetterFunctions.put("uuid", BatchLoadUsers::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<BatchLoadUsers, String>)BatchLoadUsers::setUuid);
		attributeGetterFunctions.put(
			"batchLoadUsersId", BatchLoadUsers::getBatchLoadUsersId);
		attributeSetterBiConsumers.put(
			"batchLoadUsersId",
			(BiConsumer<BatchLoadUsers, Long>)
				BatchLoadUsers::setBatchLoadUsersId);
		attributeGetterFunctions.put("groupId", BatchLoadUsers::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<BatchLoadUsers, Long>)BatchLoadUsers::setGroupId);
		attributeGetterFunctions.put("companyId", BatchLoadUsers::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<BatchLoadUsers, Long>)BatchLoadUsers::setCompanyId);
		attributeGetterFunctions.put("userId", BatchLoadUsers::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<BatchLoadUsers, Long>)BatchLoadUsers::setUserId);
		attributeGetterFunctions.put("userName", BatchLoadUsers::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<BatchLoadUsers, String>)BatchLoadUsers::setUserName);
		attributeGetterFunctions.put(
			"createDate", BatchLoadUsers::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<BatchLoadUsers, Date>)BatchLoadUsers::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", BatchLoadUsers::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<BatchLoadUsers, Date>)BatchLoadUsers::setModifiedDate);
		attributeGetterFunctions.put("name", BatchLoadUsers::getName);
		attributeSetterBiConsumers.put(
			"name",
			(BiConsumer<BatchLoadUsers, String>)BatchLoadUsers::setName);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getBatchLoadUsersId() {
		return _batchLoadUsersId;
	}

	@Override
	public void setBatchLoadUsersId(long batchLoadUsersId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_batchLoadUsersId = batchLoadUsersId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(BatchLoadUsers.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), BatchLoadUsers.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public BatchLoadUsers toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, BatchLoadUsers>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		BatchLoadUsersImpl batchLoadUsersImpl = new BatchLoadUsersImpl();

		batchLoadUsersImpl.setUuid(getUuid());
		batchLoadUsersImpl.setBatchLoadUsersId(getBatchLoadUsersId());
		batchLoadUsersImpl.setGroupId(getGroupId());
		batchLoadUsersImpl.setCompanyId(getCompanyId());
		batchLoadUsersImpl.setUserId(getUserId());
		batchLoadUsersImpl.setUserName(getUserName());
		batchLoadUsersImpl.setCreateDate(getCreateDate());
		batchLoadUsersImpl.setModifiedDate(getModifiedDate());
		batchLoadUsersImpl.setName(getName());

		batchLoadUsersImpl.resetOriginalValues();

		return batchLoadUsersImpl;
	}

	@Override
	public BatchLoadUsers cloneWithOriginalValues() {
		BatchLoadUsersImpl batchLoadUsersImpl = new BatchLoadUsersImpl();

		batchLoadUsersImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		batchLoadUsersImpl.setBatchLoadUsersId(
			this.<Long>getColumnOriginalValue("batchLoadUsersId"));
		batchLoadUsersImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		batchLoadUsersImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		batchLoadUsersImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		batchLoadUsersImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		batchLoadUsersImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		batchLoadUsersImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		batchLoadUsersImpl.setName(this.<String>getColumnOriginalValue("name"));

		return batchLoadUsersImpl;
	}

	@Override
	public int compareTo(BatchLoadUsers batchLoadUsers) {
		long primaryKey = batchLoadUsers.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof BatchLoadUsers)) {
			return false;
		}

		BatchLoadUsers batchLoadUsers = (BatchLoadUsers)object;

		long primaryKey = batchLoadUsers.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<BatchLoadUsers> toCacheModel() {
		BatchLoadUsersCacheModel batchLoadUsersCacheModel =
			new BatchLoadUsersCacheModel();

		batchLoadUsersCacheModel.uuid = getUuid();

		String uuid = batchLoadUsersCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			batchLoadUsersCacheModel.uuid = null;
		}

		batchLoadUsersCacheModel.batchLoadUsersId = getBatchLoadUsersId();

		batchLoadUsersCacheModel.groupId = getGroupId();

		batchLoadUsersCacheModel.companyId = getCompanyId();

		batchLoadUsersCacheModel.userId = getUserId();

		batchLoadUsersCacheModel.userName = getUserName();

		String userName = batchLoadUsersCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			batchLoadUsersCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			batchLoadUsersCacheModel.createDate = createDate.getTime();
		}
		else {
			batchLoadUsersCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			batchLoadUsersCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			batchLoadUsersCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		batchLoadUsersCacheModel.name = getName();

		String name = batchLoadUsersCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			batchLoadUsersCacheModel.name = null;
		}

		return batchLoadUsersCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<BatchLoadUsers, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<BatchLoadUsers, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<BatchLoadUsers, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((BatchLoadUsers)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, BatchLoadUsers>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					BatchLoadUsers.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _batchLoadUsersId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _name;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<BatchLoadUsers, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((BatchLoadUsers)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("batchLoadUsersId", _batchLoadUsersId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("name", _name);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("batchLoadUsersId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("name", 256L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private BatchLoadUsers _escapedModel;

}